version: "3"

volumes:
  db_volume:

services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: bot
    restart: always
    depends_on:
      - database
      - backend
    volumes:
      - .:/app
    env_file:
      - ./.env


  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: database
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
