FROM python

RUN apt-get update && apt-get -y upgrade
RUN apt install curl
RUN curl -y https://sh.rustup.rs -sSf | sh

ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["/bin/bash", "-c", "python check_keys.py"]
