FROM python

RUN apt-get update && apt-get -y upgrade
RUN apt install curl
RUN curl -y --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["/bin/bash", "-c", "python backend.py"]
