FROM python

RUN apt-get update && apt-get -y upgrade


WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["/bin/bash", "-c", "python backend.py"]
