all:
  children:
    xui_hosts:
      hosts:
        Russia:
          ansible_host: 45.144.30.101
          ansible_user: root
          region_code: 11
        Germany:
          ansible_host: 185.235.241.82
          ansible_user: root
          region_code: 31
        Latvia:
          ansible_host: 176.120.67.60
          ansible_user: root
          region_code: 70
        Netherlands:
          ansible_host: 94.131.106.243
          ansible_user: root
          region_code: 81
        Finland:
          ansible_host: 185.156.108.92
          ansible_user: root
          region_code: 91
        Austria:
          ansible_host: 85.208.109.86
          ansible_user: root
          region_code: 110
        UK:
          ansible_host: 45.89.111.131
          ansible_user: root
          region_code: 50
        USA:
          ansible_host: 138.124.180.34
          ansible_user: root
          region_code: 60
        France:
          ansible_host: 185.153.183.52
          ansible_user: root
          region_code: 40
        Turkey:
          ansible_host: 185.153.182.75
          ansible_user: root
          region_code: 120
        Hongkong:
          ansible_host: 74.119.193.95
          ansible_user: root
          region_code: 130



