- hosts: xui_hosts
  become: true
  roles:
    - role: reload
      vars:
        xui_container_name: "3x-ui"
        xui_clean_logs: false
        xui_kill_stray_processes: false
        xui_restart_container: true